openapi: 3.0.0
info:
  title: Web Log API
  description: Core Service APIs.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /visit:
    get:
      summary: Returns the count of website visits.
      responses:
        '200':    # status code
          description: Count of website visits
          content:
            application/json:
              schema:
                type : integer
                format: int64
                example: 54